import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Text, Integer, DateTime, ForeignKey, Index, Float
from sqlalchemy.dialects.postgresql import UUID, JSONB, TSVECTOR
from sqlalchemy.orm import declarative_base, relationship
from pgvector.sqlalchemy import Vector

Base = declarative_base()


# ── AUTH & MULTI-TENANCY ─────────────────────────
class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String(255), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime(timezone=True),
                        default=lambda: datetime.now(timezone.utc))

    documents = relationship("Document", back_populates="owner")
    golden_answers = relationship("GoldenAnswer", back_populates="owner")
    jobs = relationship("Job", back_populates="owner")
    batch_runs = relationship("BatchRun", back_populates="owner")


# ── LAYER A: KNOWLEDGE LIBRARY ───────────────────
class Document(Base):
    __tablename__ = "documents"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey(
        "users.id", ondelete="CASCADE"), index=True, nullable=True)
    filename = Column(String(255), nullable=False)
    upload_date = Column(DateTime(timezone=True),
                         default=lambda: datetime.now(timezone.utc))
    metadata_ = Column("metadata", JSONB)

    owner = relationship("User", back_populates="documents")
    chunks = relationship("Chunk", back_populates="document",
                          cascade="all, delete-orphan")


class Chunk(Base):
    __tablename__ = "chunks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_id = Column(UUID(as_uuid=True), ForeignKey(
        "documents.id", ondelete="CASCADE"))
    user_id = Column(UUID(as_uuid=True), ForeignKey(
        "users.id", ondelete="CASCADE"), index=True, nullable=True)
    content = Column(Text, nullable=False)

    # text-embedding-004 outputs 768 dimensions
    embedding = Column(Vector(768))

    # Full Text Search vector generated by Postgres
    fts_vector = Column(TSVECTOR)
    chunk_index = Column(Integer)

    document = relationship("Document", back_populates="chunks")


# ── LAYER B: GOLDEN Q&A BANK (RLHF Memory) ──────
class GoldenAnswer(Base):
    __tablename__ = "golden_answers"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey(
        "users.id", ondelete="CASCADE"), index=True, nullable=False)
    question = Column(Text, nullable=False)
    question_embedding = Column(Vector(768))  # For semantic routing
    answer = Column(Text, nullable=False)
    # Original question text for traceability
    source_question = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True),
                        default=lambda: datetime.now(timezone.utc))

    owner = relationship("User", back_populates="golden_answers")


# ── DATABASE JOB STORE (replaces in-memory dict) ─
class Job(Base):
    __tablename__ = "jobs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey(
        "users.id", ondelete="CASCADE"), index=True, nullable=True)
    # 'knowledge_ingestion' or 'rfp_batch'
    job_type = Column(String(50), nullable=False)
    status = Column(String(50), nullable=False, default="PENDING")
    progress_percentage = Column(Integer, default=0)
    message = Column(Text, nullable=True)
    result_data = Column(JSONB, nullable=True)
    error = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True),
                        default=lambda: datetime.now(timezone.utc))

    owner = relationship("User", back_populates="jobs")


# ── BATCH RUNS ───────────────────────────────────
class BatchRun(Base):
    """Lightweight record of a batch RFP run — stores the answers JSON so
    results survive container restarts and tab switches."""
    __tablename__ = "batch_runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey(
        "users.id", ondelete="CASCADE"), index=True, nullable=True)
    filename = Column(String(255), nullable=False)
    question_count = Column(Integer, nullable=False, default=0)
    created_at = Column(DateTime(timezone=True),
                        default=lambda: datetime.now(timezone.utc))
    answers = Column(JSONB, nullable=False, default=list)

    owner = relationship("User", back_populates="batch_runs")
